
version: "2"
services:
     redis:
        image: redis
     db:
        image: postgres:9.4
        environment:
          - POSTGRES_HOST_AUTH_METHOD:"trust"
     vote:
        image: prabhavagrawal/vote-app
        ports:
         - 5000:80
        depends_on:
         - redis
     result:
        image: prabhavagrawal/result-app
        ports:
          - 5001:80
     worker:
        image: prabhavagrawal/worker-app
        depends_on:
         - redis
         - db
